# Parquet Playground (Doom dataset)

Use this notebook to inspect one parquet shard and decode byte fields.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import pyarrow.parquet as pq

In [2]:
DATA_DIR = Path('/mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed')
parquet_files = sorted(DATA_DIR.rglob('*.parquet'))
print(f'Found {len(parquet_files)} parquet files under {DATA_DIR}')
print('First 5 files:')
for p in parquet_files[:5]:
    print(' -', p)

Found 125 parquet files under /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed
First 5 files:
 - /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed/gpu_0_file_0/combined_parquet_dataset/worker_0/data_chunk_0.parquet
 - /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed/gpu_0_file_0/combined_parquet_dataset/worker_0/data_chunk_1.parquet
 - /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed/gpu_0_file_0/combined_parquet_dataset/worker_0/data_chunk_2.parquet
 - /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed/gpu_0_file_0/combined_parquet_dataset/worker_0/data_chunk_3.parquet
 - /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed/gpu_0_file_16/combined_parquet_dataset/worker_0/data_chunk_0.parquet

In [3]:
# Pick one file to inspect
file_idx = 0
parquet_path = parquet_files[file_idx]

pf = pq.ParquetFile(parquet_path)
print('FILE:', parquet_path)
print('ROWS:', pf.metadata.num_rows)
print('ROW_GROUPS:', pf.num_row_groups)
print('SCHEMA:')
print(pf.schema)

df = pq.read_table(parquet_path).to_pandas()
with pd.option_context('display.max_columns', 50, 'display.width', 200):
    display(df.head(3))

FILE: /mnt/weka/home/hao.zhang/mhuo/traindata_0204_1600/preprocessed/gpu_0_file_0/combined_parquet_dataset/worker_0/data_chunk_0.parquet
ROWS: 8
ROW_GROUPS: 1
SCHEMA:
<pyarrow._parquet.ParquetSchema object at 0x153cf9714600>
required group field_id=-1 schema {
  optional binary field_id=-1 id (String);
  optional binary field_id=-1 vae_latent_bytes;
  optional group field_id=-1 vae_latent_shape (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional binary field_id=-1 vae_latent_dtype (String);
  optional binary field_id=-1 clip_feature_bytes;
  optional group field_id=-1 clip_feature_shape (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional binary field_id=-1 clip_feature_dtype (String);
  optional binary field_id=-1 first_frame_latent_bytes;
  optional group field_id=-1 first_frame_latent_shape (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional binary field_id=-1 first_frame_latent_dtype (String);
  optional binary field_id=-1 mouse_cond_bytes;
  optional group field_id=-1 mouse_cond_shape (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional binary field_id=-1 mouse_cond_dtype (String);
  optional binary field_id=-1 keyboard_cond_bytes;
  optional group field_id=-1 keyboard_cond_shape (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional binary field_id=-1 keyboard_cond_dtype (String);
  optional binary field_id=-1 pil_image_bytes;
  optional group field_id=-1 pil_image_shape (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional binary field_id=-1 pil_image_dtype (String);
  optional binary field_id=-1 file_name (String);
  optional binary field_id=-1 caption (String);
  optional binary field_id=-1 media_type (String);
  optional int64 field_id=-1 width;
  optional int64 field_id=-1 height;
  optional int64 field_id=-1 num_frames;
  optional double field_id=-1 duration_sec;
  optional double field_id=-1 fps;
}

,id,vae_latent_bytes,vae_latent_shape,vae_latent_dtype,clip_feature_bytes,clip_feature_shape,clip_feature_dtype,first_frame_latent_bytes,first_frame_latent_shape,first_frame_latent_dtype,mouse_cond_bytes,mouse_cond_shape,mouse_cond_dtype,keyboard_cond_bytes,keyboard_cond_shape,keyboard_cond_dtype,pil_image_bytes,pil_image_shape,pil_image_dtype,file_name,caption,media_type,width,height,num_frames,duration_sec,fps
0,000000,"b'P\x1e\xbc\xbe\x1bw\xcf\xbecg\x0e\xbf""\xb3\xf...","[16, 20, 44, 80]",float32,b'\xef\x04\x89\xbf!\x19:>^\x8a\xef>\xfd\xd8\x0...,"[257, 1280]",float32,b'\xe4\x94\r>\x8d\xb4\xff=\xf9\xef\x91=\x94\x8...,"[16, 20, 44, 80]",float32,b'\x00\x00\x00\x00\xcd\xcc\xcc\xbd\x00\x00\x00...,"[77, 2]",float32,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80...,"[77, 6]",float32,b'',[],,000000,,video,352,640,20,3.08,25.0
1,000001,"b'\xe6\x9a,\xbf\xc5\x1c$\xbf\x14\x1f!\xbf!\x1c...","[16, 20, 44, 80]",float32,b'a\x05I\xbf\xe4\xbc\xe0=\xf9[\xb0>\xb4\x90\x8...,"[257, 1280]",float32,b'\x9e\xd8\xf0<\xcb\xa2(=\x9c\x9d9={Z\xf0\xbbq...,"[16, 20, 44, 80]",float32,b'\xcd\xcc\xcc\xbd\x00\x00\x00\x00\x00\x00\x00...,"[77, 2]",float32,b'\x00\x00\x00\x00\x00\x00\x80?\x00\x00\x00\x0...,"[77, 6]",float32,b'',[],,000001,,video,352,640,20,3.08,25.0
2,000002,b'p\x0e\xd7\xbeFM\xc5\xbe[\x9e3\xbf\xa0Q)\xbf\...,"[16, 20, 44, 80]",float32,b'Q\xbe\xbe\xbe\x98&\x9c>\xc8\xbc.>\xcd\xcd\x9...,"[257, 1280]",float32,b'}\xee\xf4=\x98\x10\x07>\x117\xa1<3\x14\x0b=\...,"[16, 20, 44, 80]",float32,b'\x00\x00\x00\x00\xcd\xcc\xcc\xbd\x00\x00\x00...,"[77, 2]",float32,b'\x00\x00\x00\x00\x00\x00\x80?\x00\x00\x00\x0...,"[77, 6]",float32,b'',[],,000002,,video,352,640,20,3.08,25.0

In [4]:
def decode_blob(row, prefix):
    b = row[f'{prefix}_bytes']
    shape = row[f'{prefix}_shape']
    dtype = row[f'{prefix}_dtype']
    if b is None or len(b) == 0:
        return None
    arr = np.frombuffer(b, dtype=np.dtype(dtype))
    return arr.reshape(shape)

row0 = df.iloc[0]
for k in ['vae_latent', 'clip_feature', 'first_frame_latent', 'mouse_cond', 'keyboard_cond']:
    arr = decode_blob(row0, k)
    if arr is None:
        print(f'{k}: empty')
    else:
        print(f'{k}: shape={arr.shape}, dtype={arr.dtype}, min={arr.min():.4f}, max={arr.max():.4f}')

mouse = decode_blob(row0, 'mouse_cond')
keyboard = decode_blob(row0, 'keyboard_cond')

if mouse is not None:
    print('\nmouse_cond (first 12 rows):')
    print(np.array2string(mouse[:12], precision=3, suppress_small=True))
    print('mouse unique values:', np.unique(np.round(mouse, 3)))
    display(pd.DataFrame(mouse, columns=['mouse_dx', 'mouse_dy']).head(20))

if keyboard is not None:
    print('\nkeyboard_cond (first 12 rows):')
    print(np.array2string(keyboard[:12], precision=3, suppress_small=True))
    print('keyboard unique values:', np.unique(np.round(keyboard, 3)))
    key_cols = ['key_w', 'key_a', 'key_s', 'key_d', 'mouse_l', 'mouse_r']
    if keyboard.shape[1] == len(key_cols):
        display(pd.DataFrame(keyboard, columns=key_cols).head(20))
    else:
        display(pd.DataFrame(keyboard).head(20))

vae_latent: shape=(16, 20, 44, 80), dtype=float32, min=-4.8036, max=5.6870
clip_feature: shape=(257, 1280), dtype=float32, min=-6.0797, max=11.8130
first_frame_latent: shape=(16, 20, 44, 80), dtype=float32, min=-2.0785, max=2.7621
mouse_cond: shape=(77, 2), dtype=float32, min=-0.1000, max=0.1000
keyboard_cond: shape=(77, 6), dtype=float32, min=0.0000, max=1.0000

mouse_cond (first 12 rows):
[[ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]
 [ 0.  -0.1]]
mouse unique values: [-0.1  0.   0.1]

    mouse_dx  mouse_dy
0        0.0      -0.1
1        0.0      -0.1
2        0.0      -0.1
3        0.0      -0.1
4        0.0      -0.1
5        0.0      -0.1
6        0.0      -0.1
7        0.0      -0.1
8        0.0      -0.1
9        0.0      -0.1
10       0.0      -0.1
11       0.0      -0.1
12       0.0      -0.1
13       0.0       0.1
14       0.0       0.1
15       0.0       0.1
16       0.0       0.1
17       0.0       0.1
18       0.0       0.1
19       0.0       0.1

keyboard_cond (first 12 rows):
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
keyboard unique values: [0. 1.]

    key_w  key_a  key_s  key_d  mouse_l  mouse_r
0     0.0    0.0    1.0    0.0      0.0      0.0
1     0.0    0.0    0.0    1.0      0.0      0.0
2     0.0    0.0    0.0    1.0      0.0      0.0
3     0.0    0.0    0.0    1.0      0.0      0.0
4     0.0    0.0    0.0    1.0      0.0      0.0
5     0.0    0.0    0.0    1.0      0.0      0.0
6     0.0    0.0    0.0    1.0      0.0      0.0
7     0.0    0.0    0.0    1.0      0.0      0.0
8     0.0    0.0    0.0    1.0      0.0      0.0
9     0.0    0.0    0.0    1.0      0.0      0.0
10    0.0    0.0    0.0    1.0      0.0      0.0
11    0.0    0.0    0.0    1.0      0.0      0.0
12    0.0    0.0    0.0    1.0      0.0      0.0
13    1.0    0.0    0.0    0.0      0.0      0.0
14    1.0    0.0    0.0    0.0      0.0      0.0
15    1.0    0.0    0.0    0.0      0.0      0.0
16    1.0    0.0    0.0    0.0      0.0      0.0
17    1.0    0.0    0.0    0.0      0.0      0.0
18    1.0    0.0    0.0    0.0      0.0      0.0
19    1.0    0.0    0.0    0.0      0.0      0.0